from __future__ import annotations

from typing import List

# Quest patrons (the people/factions hiring you). Keep this larger than the 20-chapter campaign.
PATRONS: List[str] = [
    "the Greyhaven Archivists",
    "the Lantern Order",
    "a nervous baron from the Shattered Marches",
    "a masked collector with a velvet purse",
    "the Amber Collegium",
    "a temple prior with ash on their sleeves",
    "the Dawnwardens of Saint Ash",
    "a retired adventurer with a bitter laugh",
    "a dockside guildmaster with too many rings",
    "the Oracular Circle of Highmere",
    "a witch-hunter with a book of names",
    "the Silent Choir (their letters arrive without seals)",
    "a wandering cartographer chasing a lost map",
    "the Silvered Oath (a knightly company in exile)",
    "a magistrate who won't sign their own name",
    "a librarian-lich's repentant apprentice",
    "a river-priest who speaks only in bargains",
    "the Hearthguard of Emberfall",
    "the Glasswright Syndicate",
    "a duelist sworn to settle an old debt",
    "a scribe who claims the dungeon is moving",
    "the Watchers of the Seventh Veil",
    "a spice-merchant whose smile never reaches their eyes",
    "a fugitive noble with a bloodline curse",
    "the Stonebinders (masons who know too much)",
    "an undertaker with holy water on their gloves",
    "a mercenary captain missing half their company",
    "the Guild of Keys and Wards",
    "a star-augur who reads omens in soot",
    "the Sisters of the Black Taper",
    "a brewer whose cellar opens onto older stairs",
    "the Border Wardens of the Far March",
    "a scholar of forbidden pacts",
    "the Ashen Court (they pay in favors, not coin)",
    "a pilgrim bearing a cracked relic",
    "a diplomat from a city you can't find on any map",
]

# Places to reference in story intros. Also keep this larger than the campaign length.
PLACES: List[str] = [
    "Greyhaven",
    "Emberfall",
    "Highmere",
    "Duskbridge",
    "Ravenscar",
    "Mistwatch",
    "Sableford",
    "Thornwall",
    "Cindergate",
    "Stoneharbor",
    "Moonfall",
    "Wyrmrest",
    "Glassmere",
    "Brightwater",
    "Ashford",
    "Hollowmarsh",
    "Frostmere",
    "Gloamstead",
    "Copperhollow",
    "Stormbreak",
    "Crowncross",
    "Witchfen",
    "Blackbriar",
    "Oakhurst",
    "Eelwake",
    "Old Barrow",
    "Kingsgrove",
    "Sunspire",
    "Lanternrise",
    "Grimport",
    "Thistledown",
    "Saltwick",
    "Ebonreach",
    "Pale Hollow",
    "Vellum Row",
    "Shatterford",
]

PRISONERS: List[str] = [
    "a missing lantern-scout",
    "a captured apprentice",
    "a wounded sellsword",
    "a chained acolyte",
    "a courier with a sealed letter",
    "a glasswright's journeyman",
    "a hedge-mage with singed sleeves",
    "a priest's attendant clutching a prayer-bead",
    "a deserter who swears they saw the boss room move",
    "a scholar who refuses to say what they read",
]
